name: Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build Docker image
      run: docker build -t oneeurofilter ./docker
    - name: Run tests
      run: docker run --rm --mount type=bind,source=${{ github.workspace }},target=/mnt/1euro oneeurofilter bash -c "cd /mnt/1euro && make"

